config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        patch 'set_user_activation'
      end
    end
    resources :clients do
    end
    resources :admins, only: [:index], as: 'root'
    resources :projects do
      resources :payments do
      end
      resources :time_logs do
      end
      resources :comments do
      end
    end
  end
  namespace :api do
    namespace :v1 do
      namespace :sessions do
        post 'create'
        delete 'destroy'
      end
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
      end
      resources :clients
    end
  end
  resources :projects do
    resources :payments do
    end
    resources :time_logs do
    end
    resources :comments do
    end
  end
  resources :clients do
  end

  match '*path', to: 'exceptions#catch_404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# comment
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :body, presence: true

  paginates_per 5
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminsController
  before_action :set_commentable
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comments = @commentable.comments.last(5)
    @comment = @commentable.comments.new
  end

  def edit; end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @comments = @commentable.comments.last(5)
    @all_comments = @commentable.comments.page(params[:comment_page]).includes(:user)
  end

  def update
    if @comment.update(comment_params)
      redirect_to [:admin, @commentable], notice: 'Comment succesfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to [:admin, @commentable]
  end

  private

  def find_commentable
    params.each do |name, value|
      return Regexp.last_match(1).classify.constantize.find(value) if name =~ /(.+)_id$/
    end
  end

  def set_commentable
    @commentable = find_commentable
  end

  def set_comment
    @commentable = find_commentable
    @comment = @commentable.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::APIController
  before_action :set_commentable

  def index
    successful_response(CommentSerializer.new(@commentable.comments.includes(:user).page(params[:page])).serializable_hash)
  end

  private

  def set_commentable
    if @current_user.user?
      @commentable = @current_user.projects.find(params[:project_id])
    else
      @commentable = Project.find(params[:project_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comments = @commentable.comments.last(5)
    @comment = @commentable.comments.new
  end

  def edit; end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @comments = @commentable.comments.last(5)
    @all_comments = @commentable.comments.page(params[:comment_page]).includes(:user)
  end

  def update
    if @comment.update(comment_params)
      redirect_to @commentable, notice: 'Comment succesfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to @commentable
  end

  private

  def set_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
    authorize @commentable, :show?
  end

  def set_comment
    @comment = @commentable.comments.find(params[:id])
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/admin/comments/_all_comments.html.erb
<div class="card" rounded-0">
  <% @all_comments.each do |comment| %>
    <div class="card-header p-0">
      <div class="row mx-1 mt-2">
        <div class="col-6 font-weight-bold small">  <%= comment.user.username %></div>
        <div class="col-6 small">
          <div class="row float-right">
            <p class="pr-2"><%= comment.created_at.to_date %>
              <%= link_to edit_admin_project_comment_path(@commentable, comment), class: "ml-2" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to admin_project_comment_path(@commentable, comment), class: "ml-2", method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body small">
      <%= comment.body %>
    </div>
  <% end %>
</div>

app/views/admin/comments/_all_new_comments.html.erb
<div class="row">
  <div class="col-12">
    <div id="load-project-comments">
      <%= render 'admin/comments/all_comments' %>
    </div>
    <div class="row mt-4">
      <div class="col-12">
        <%= form_for [:admin, @project, @project.comments.build], remote: true do |f| %>
          <div id="errors"></div>
          <div class="form-group">
            <div class="form-label-group">
              <%= f.text_area :body, id: "commentbox", class: "form-control" , placeholder: 'Write comment...' %>
            </div>
          </div>
          <%= f.submit class: "btn btn-dark btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="load-pagination">
  <%= render 'admin/comments/pagination', :param_name => "comment_page" %>
</div>

app/views/admin/comments/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Recent Comments</h5>
  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<div class="modal-body">
  <div id="load-comments">
    <%= render 'recent_comments' %>
  </div>
  <div class="mt-3">
    <%= form_for [:admin, @commentable, @comment], :remote => true do |f| %>
      <div id="errors"></div>
      <div class="form-group">
        <div class="form-label-group">
          <%= f.text_area :body, id: "commentbox", class: "form-control" , placeholder: 'Write comment...' %>
        </div>
      </div>
      <%= f.submit class: "btn btn-dark btn-block" %>
    <% end %>
  </div>
</div>
<div class="modal-footer">
  <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
</div>

app/views/admin/comments/_pagination.html.erb
<div id="paginate-link" class="float-right mt-4">
  <%= paginate @all_comments,  :param_name => "comment_page" %>
</div>

app/views/admin/comments/_recent_comments.html.erb
<% if @comments.any? %>
  <div class="card rounded-0">
    <% @comments.each do |comment| %>
      <div class="card-header p-0">
        <div class="row mx-1 my-1">
          <div class="col-6 font-weight-bold small">  <%= comment.user.username %></div>
          <div class="col-6 small text-right"><%= comment.created_at.to_date %></div>
        </div>
      </div>
      <div class="card-body small p-0 mx-4 my-2"><%= comment.body %>
      </div>
    <% end %>
  </div>
  <%= link_to 'View all comments', admin_project_path(@commentable), class: "btn btn-info btn-block mt-3" %>
<% end %>

app/views/admin/comments/create.js.erb
$('#errors').html("<%= j render 'layouts/error_messages', object: @comment %>");
<% if @comment.persisted? %>
  $('#load-comments').html("<%= j render 'recent_comments', object: @comments %>");
  $('#load-project-comments').html("<%= j render 'all_comments', object: @all_comments %>");
  $('.flash-messages').html("<%= j render 'layouts/flash_messages', flash: flash %>");
  $('#commentbox').val("");
  $('#commentbox').placeholder('Write comment...');
<% end %>

app/views/admin/comments/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span">Comment</span>
  </li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<h2>Edit Comment</h2>
<hr>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Update your Comment</div>
    <div class="card-body">
      <%= form_for [:admin, @commentable, @comment] do |f| %>
        <%= render '/layouts/error_messages', object: @comment %>
        <div class="form-group">
          <div class="form-label-group">
            <%= f.text_area :body, id: "commentbox", class: "form-control" , placeholder: 'Write comment...' %>
          </div>
        </div>
        <%= f.submit class: "btn btn-dark btn-block" %>
      <% end %>
    </div>
  </div>
</div>