config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        patch 'set_user_activation'
      end
    end
    resources :clients do
    end
    resources :admins, only: [:index], as: 'root'
    resources :projects do
      resources :payments do
      end
      resources :time_logs do
      end
      resources :comments do
      end
    end
  end
  namespace :api do
    namespace :v1 do
      namespace :sessions do
        post 'create'
        delete 'destroy'
      end
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
      end
      resources :clients
    end
  end
  resources :projects do
    resources :payments do
    end
    resources :time_logs do
    end
    resources :comments do
    end
  end
  resources :clients do
  end

  match '*path', to: 'exceptions#catch_404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :projects, dependent: :destroy
  after_save ThinkingSphinx::RealTime.callback_for(:client)
  after_save ThinkingSphinx::RealTime.callback_for(:project, [:projects])

  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+\z/.freeze

  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_USERNAME_REGEX }, length: { minimum: 5, maximum: 30 }
  validates :company, presence: true, length: { minimum: 5, maximum: 30 }, format: { with: VALID_USERNAME_REGEX }

  def self.search_with(params)
    params = {} if params.blank?
    search_params = default_search_options(params)
    search(Riddle.escape(params[:search].to_s), search_params)
  end

  def self.default_search_options(pagination_options)
    {
      page: pagination_options[:page],
      per_page: 10
    }
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::AdminsController
  before_action :set_client, only: %i[show edit update destroy]

  def index
    @clients = Client.search_with(params)
  end

  def show; end

  def new
    @client = Client.new
  end

  def edit; end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to admin_clients_path(@client), notice: 'Client succesfully created!'
    else
      render 'new'
    end
  end

  def update
    if @client.update(client_params)
      redirect_to admin_client_path(@client)
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to admin_clients_path
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :company)
  end
end

app/controllers/api/v1/clients_controller.rb
class Api::V1::ClientsController < Api::APIController

  def index
    successful_response(ClientSerializer.new(Client.search_with(params)).serializable_hash)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  def index
    @clients = Client.search_with(params)
  end

  def show; end

  def new
    @client = Client.new
    authorize @client
  end

  def edit; end

  def create
    @client = Client.new(client_params)
    authorize @client
    if @client.save
      redirect_to clients_path(@client), notice: 'Client succesfully created!'
    else
      render 'new'
    end
  end

  def update
    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def set_client
    @client = Client.find(params[:id])
    authorize @client
  end

  def client_params
    params.require(:client).permit(:name, :company)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def show_project_link(show, project)
    if show
      link_to project.name, project_path(project) 
    else
      project.name
    end
  end
end

app/views/admin/clients/_form.html.erb
<div class="card-body">
  <%= form_for [:admin, @client] do |f| %>
    <div id="errors">
      <%= render 'layouts/error_messages', object: @client %>
    </div>
    <div class="form-group">
      <div class="form-label-group">
        <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="form-group">
      <div class="form-label-group">
        <%= f.text_field :company, class: "form-control", placeholder: 'Company' %>
        <%= f.label :company %>
      </div>
    </div>
    <%= f.submit class: "btn btn-dark btn-block" %>
  <% end %>
</div>

app/views/admin/clients/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Clients</span>
  </li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<h2>Update Client</h2>
<hr>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Update Client Info</div>
      <%= render 'form' %>
  </div>
</div>

app/views/admin/clients/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Clients</span>
  </li>
  <li class="breadcrumb-item active">Index</li>
</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
    Listing clients
    <%= link_to '+', new_admin_client_path, class: "btn btn-dark float-right" %>
  </div>
  <div class="card-body">
    <%= form_tag admin_clients_path, method: :get do %>
      <div class="field mb-4">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search", aria: {label:"Search", describedby: "basic-addon1"} %>
      </div>
    <% end %>
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th class="text-center">Name</th>
            <th class="text-center">Company</th>
            <th class="text-center">Show</th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
            <tr>
              <td class="text-center"><%= client.name %></td>
              <td class="text-center"><%= client.company %></td>
              <td class="text-center">
                <%= link_to admin_client_path(client) do %>
                  <h5><i class="fas fa-info-circle text-dark"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to edit_admin_client_path(client) do %>
                  <h5><i class="fas fa-pen text-dark"></i></h5>
                <% end %></td>
              <td class="text-center">
                <%= link_to admin_client_path(client), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <h5><i class="fas fa-trash text-danger"></i></h5>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="my-4">
        <%= paginate @clients, class: "pagination" %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="destroyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

app/views/admin/clients/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Clients</span>
  </li>
  <li class="breadcrumb-item active">Create</li>
</ol>

<h2>Create Client</h2>
<hr>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Add a client</div>
      <%= render 'form' %>
  </div>
</div>

app/views/admin/clients/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Clients</span>
  </li>
  <li class="breadcrumb-item active">Details</li>
</ol>

<h2><%= @client.company %> Company</h2>
<hr>

<div class="container">
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-table"></i>
      <%= @client.name %> projects
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th class="text-center">Projects</th>
            </tr>
          </thead>
          <tbody>
            <% @client.projects.each do |project| %>
              <tr>
                <td class="text-center"><%= link_to project.name, admin_project_path(project) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>