config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  namespace :admin do
    resources :users do
      member do
        patch 'set_user_activation'
      end
    end
    resources :clients do
    end
    resources :admins, only: [:index], as: 'root'
    resources :projects do
      resources :payments do
      end
      resources :time_logs do
      end
      resources :comments do
      end
    end
  end
  namespace :api do
    namespace :v1 do
      namespace :sessions do
        post 'create'
        delete 'destroy'
      end
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
      end
      resources :clients
    end
  end
  resources :projects do
    resources :payments do
    end
    resources :time_logs do
    end
    resources :comments do
    end
  end
  resources :clients do
  end

  match '*path', to: 'exceptions#catch_404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :client
  has_many :payments, dependent: :destroy
  has_many :time_logs, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  after_save ThinkingSphinx::RealTime.callback_for(:project)

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 30 }

  def self.max_five_projects
    left_outer_joins(:payments, :time_logs).select('projects.*, SUM(payments.amount) AS amount_sum, SUM(time_logs.hours) AS hours_sum').group(:id).order('sum(payments.amount) desc').first(5)
  end

  def self.min_five_projects
    left_outer_joins(:payments, :time_logs).select('projects.*, SUM(payments.amount) AS amount_sum, SUM(time_logs.hours) AS hours_sum').group(:id).order('sum(payments.amount)').first(5)
  end

  def self.current_month_payments
    left_outer_joins(:payments).group(:name).where(payments: {created_at: Date.today.beginning_of_month..Date.today.end_of_month} ).sum(:amount)
  end

  def self.current_month_time_logs
    left_outer_joins(:time_logs).group(:name).where(time_logs: {created_at: Date.today.beginning_of_month..Date.today.end_of_month} ).sum(:hours)
  end

  def self.search_with(params, user = nil)
    params = {} if params.blank?
    search_params = default_search_options(params)
    search_params[:with][:user_ids] = user.id if user && user.user?
    search(Riddle.escape(params[:search].to_s), search_params)
  end

  def self.default_search_options(pagination_options)
    {
      with: {},
      page: pagination_options[:page],
      per_page: 10,
      sql: {
        include: [:client]
      }
    }
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminsController
  before_action :set_client, only: %i[new create edit update]
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_project_users, only: %i[new edit create update]

  def index
    @projects = Project.search_with(params)
  end

  def show
    @commentable = @project
    @all_comments = @project.comments.page(params[:comment_page]).includes(:user)
    @attachments = @project.attachments
    @all_time_logs = @project.time_logs.page(params[:time_log_page]).includes(:user)
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to admin_projects_path(@project), notice: 'Project succesfully created!'
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to admin_project_path(@project), notice: 'Project succesfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to admin_projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_client
    @clients = Client.all
  end

  def set_project_users
    @users = User.where(role: 'user')
  end

  def project_params
    params.require(:project).permit(:name, :client_id, user_ids: [], attachments_attributes: %i[id avatar _destroy])
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::APIController
  before_action :set_project, only: %i[show]
  before_action :set_serializer_options, only: %i[show]

  def index
    successful_response(Project.search_with(params, @current_user))
  end

  def show
    unsucessful_response(404, 'Not Authorized') unless @project

    successful_response(ProjectSerializer.new(@project, @options).serializable_hash)
  end

  private

  def set_serializer_options
    @options = { params: {} }
    @options[:params][:comment_page] = params[:comment_page]
    @options[:params][:time_log_page] = params[:time_log_page]
    @options[:include] = [:client, :users, :payments]
  end

  def set_project
    if @current_user.user?
      @project = @current_user.projects.find(params[:id])
    else
      @project = Project.find(params[:id])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project_users, only: %i[new edit create update]
  before_action :set_client, only: %i[new create edit update]
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.search_with(params, current_user)
  end

  def show
    @commentable = @project
    @all_comments = @project.comments.page(params[:comment_page]).includes(:user)
    @attachments = @project.attachments
    @all_time_logs = @project.time_logs.page(params[:time_log_page]).includes(:user)
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit; end

  def create
    @project = Project.new(project_params)
    authorize @project
    if @project.save
      redirect_to projects_path(@project), notice: 'Project succesfully created!'
    else
      set_project_users
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Project succesfully updated!'
    else
      set_project_users
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def set_client
    @clients = Client.all
  end

  def set_project_users
    @users = User.where(role: 'user')
  end

  def project_params
    params.require(:project).permit(:name, :client_id, user_ids: [], attachments_attributes: %i[id avatar _destroy])
  end
end

app/views/admin/projects/_attachment_fields.html.erb
<div class='nested-fields'>
  <% if f.object.avatar.exists? %>
    <%= link_to f.object.avatar_file_name, f.object.avatar.url(:original) %>
  <% else %>
    <div class="field">
      <%= f.file_field :avatar %>
    </div>
  <% end %>
  <%= link_to_remove_association "remove attachment", f, class: "btn btn-warning my-3" %>
</div>

app/views/admin/projects/_form.html.erb
<div class="card-body">
  <%= form_for [:admin, @project], html: { multipart: true } do |f| %>
    <div id="errors">
      <%= render 'layouts/error_messages', object: @project %>
    </div>
    <div class="form-group">
      <div class="form-label-group">
        <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="mb-4">
          <%= f.fields_for :attachments  do |attachment| %>
            <%= render 'attachment_fields', :f => attachment %>
          <% end %> 
          <div class='links'>
            <%= link_to_add_association 'add attachment', f, :attachments, class: "btn btn-info" %>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="form-row mb-4">
          <div class="col-6">
            <p class="text-right mt-1">Client:</p>
          </div>
          <div class="col-6">
            <%= collection_select(:project, :client_id, @clients, :id, :name, {}, { class: "form-control" }) %>
          </div>
        </div>
        <div class="float-right mb-4">
          Users:
          <%= f.collection_select(:user_ids, @users, :id, :username, {}, {multiple: true, class: "chosen-select btn btn-info"}) %>
        </div>
      </div>
    </div>
    <%= f.submit class: "btn btn-dark btn-block" %>
  <% end %>
</div>

app/views/admin/projects/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Projects</span>
  </li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<h2>Update Project</h2>
<hr>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Update Project Info</div>
      <%= render 'form' %>
  </div>
</div>
<br/><br/>

app/views/admin/projects/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Dashboard</span>
  </li>
  <li class="breadcrumb-item active">Projects</li>
</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
    Listing projects
    <%= link_to '+', new_admin_project_path, class: "btn btn-dark float-right" %>
  </div>
  <div class="card-body">
    <%= form_tag admin_projects_path, method: :get do %>
      <div class="field mb-4">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search", aria: {label:"Search", describedby: "basic-addon1"} %>
      </div>
    <% end %>
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th class="text-center">Name</th>
            <th class="text-center">Clients</th>
            <th class="text-center" colspan="2">Payments</th>
            <th class="text-center" colspan="2">Time Logs</th>
            <th class="text-center">Comments</th>
            <th class="text-center">Show</th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td class="text-center"><%= project.name %></td>
              <td class="text-center"><%= link_to project.client.name, admin_client_path(project.client) %></td>
              <td class="text-center">
                <%= link_to new_admin_project_payment_path(project), { remote: true, data: { toggle: 'modal', target: '#myModal' }} do %>
                  <h5><i class="fas fa-plus-circle text-success""></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to admin_project_payments_path(project) do %>
                  <h5><i class="fas fa-info-circle text-success"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to new_admin_project_time_log_path(project), { remote: true, data: { toggle: 'modal', target: '#myModal' }} do %>
                  <h5><i class="fas fa-calendar-plus text-dark"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to admin_project_path(project) do %>
                  <h5><i class="fas fa-info-circle text-dark"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to new_admin_project_comment_path(project), { remote: true, data: { toggle: 'modal', target: '#myModal' }} do %>
                  <h5><i class="fas fa-fw fa-comments text-primary"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to admin_project_path(project) do %>
                  <h5><i class="fas fa-info-circle text-dark"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to edit_admin_project_path(project) do %>
                  <h5><i class="fas fa-pen text-dark"></i></h5>
                <% end %>
              </td>
              <td class="text-center">
                <%= link_to admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <h5><i class="fas fa-trash text-danger"></i></h5>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="my-4 float-right">
        <%= paginate @projects, class: "pagination" %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
<div class="modal fade" id="destroyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

app/views/admin/projects/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Projects</span>
  </li>
  <li class="breadcrumb-item active">Create</li>
</ol>

<h2>Create Project</h2>
<hr>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Add a project</div>
      <%= render 'form' %>
  </div>
</div>
<br/><br/>

app/views/admin/projects/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <span>Projects</span>
  </li>
  <li class="breadcrumb-item active">Details</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto my-5">
    <div class="card-header"><%= @project.name %></div>
    <div class="card-body text-center">
      <p>
        <span class="font-weight-light font-italic">Total Payment:</span>
        <span class="font-weight-bold"><%= @project.payments.sum(:amount) %></span>
      </p>
      <p>
        <span class="font-weight-light font-italic">Client: </span>
        <span class="font-weight-bold"><%= @project.client.name %></span>
      </p>
      <% @attachments.each do |attachment| %>
        <%= link_to attachment.avatar_file_name, attachment.avatar.url(:original) %>
      <% end %>
    </div>
  </div>
  <h5>Time logs</h5>
  <hr>
  <div class="row mt-5">
    <div class="col-12">
      <%= render 'admin/time_logs/project_time_logs' %>
    </div>
  </div>
  <h5>Comments</h5>
  <hr>
  <div class="row mt-5">
    <div class="col-12">
      <%= render 'admin/comments/all_new_comments' %>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>